version: '3.5'

services:
  postgresql:
      image: postgres:latest
      restart: always
      ports:
        - '5433:5432'
      volumes:
        - ./volumes/postgresql:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: user1
        POSTGRES_PASSWORD: 12345678
        POSTGRES_DB: chbox


